CREATE TABLE [dbo].[Address]
(
	[Id] BIGINT IDENTITY (1, 1) NOT NULL,
	[City] NVARCHAR (100)  NOT NULL,
	[Street] NVARCHAR (100)  NOT NULL,
	CONSTRAINT [PK_Address] PRIMARY KEY CLUSTERED ([Id] ASC)
)
