CREATE TABLE [dbo].[Press]
(
	[Id] BIGINT IDENTITY (1, 1) NOT NULL,
	[Name] NVARCHAR (100)  NOT NULL,
	[Email] NVARCHAR (100)  NULL,
	[CategoryId] NVARCHAR(100) NOT NULL,
	CONSTRAINT [PK_Press] PRIMARY KEY CLUSTERED ([Id] ASC))
